language: node_js
node_js:
  - 14

install:
  - echo "nothing to install"
  - npm install ui5-middleware-livereload @ui5/cli serverless

before_script:
  - echo "nothing"

script:
  - pwd
  - which npm
  - ls -l
  - cd client
  - pwd
  - which npm
  - cd ..

after_success:
  - echo "nothing todo so far"



