language: node_js
node_js:
  - 14

install:
  - echo "nothing to install"
  - npm install ui5-middleware-livereload
  - npm install @ui5/cli
  - npm install serverless

before_script:
  - echo "nothing"

script:
  - pwd
  - ls -l
  - cd client
  - ls -l
  - ui5 --config ./uimodule/ui5.yaml build
  - cd ..

after_success:
  - echo "nothing todo so far"



