language: node_js
node_js:
  - 14

install:
  - echo "nothing to install"
  - npm install ui5-middleware-livereload @ui5/cli serverless
  - aws --version

before_script:
  - echo "nothing"
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

script:
  - pwd
  - which npm
  - ls -l
  - cd client
  - pwd
  - ls -l
  - which npm
  - npm install
  - ui5 --config ./uimodule/ui5.yaml build
  - cd ..
  - cd backend
  - pwd
  - ls -l
  - npm install
  - sls deploy -v
  - cd ..

after_success:
  - echo "nothing todo so far"



