language: node_js
node_js:
  - 14

install:
  npm install -g @ui5/cli
  npm install -g serverless

before_script:
  - echo "not tests"

script:
  - pwd
  - ls -l
  - npm install ./client --prefix ./client/node_modules
  - cd client
  - ui5 --config ./client/uimodule/ui5.yaml build
  - cd ..

after_success:
  - echo "nothing todo so far"



