language: node_js
node_js:
  - 14

install:
  - echo "nothing to install"
  - npm install ui5-middleware-livereload @ui5/cli serverless

before_script:
  - echo "nothing"

script:
  - pwd
  - ls -l
  - ui5 --config ./client/uimodule/ui5.yaml build
  - cd ..

after_success:
  - echo "nothing todo so far"



