language: node_js
node_js:
  - 14

install:
  - echo "nothing to install"
before_script:
  - echo "not tests"

script:
  - pwd
  - ls -l
  - npm install ./client --prefix ./client/node_modules
  - cd client
  - npm install
  - ls -l
  - ui5 --config ./uimodule/ui5.yaml build
  - cd ..

after_success:
  - echo "nothing todo so far"



